import type { NextConfig } from "next";
import path from "path";

const nextConfig: NextConfig = {
  turbopack: {
    root: path.resolve(__dirname),
  },
  images: {
    remotePatterns: [
      { protocol: 'https', hostname: 'steamcdn-a.akamaihd.net' },
      { protocol: 'https', hostname: 'cdn.cloudflare.steamstatic.com' },
      { protocol: 'https', hostname: 'cdn.steamusercontent.com' },
      { protocol: 'https', hostname: '*.steamstatic.com' },
      { protocol: 'https', hostname: '*.akamaihd.net' },
      { protocol: 'https', hostname: 'cdn.pandascore.co' },
      { protocol: 'https', hostname: 'cdn-api.pandascore.co' },
      { protocol: 'https', hostname: '*.pandascore.co' },
      { protocol: 'https', hostname: '*.supabase.co' },
      { protocol: 'https', hostname: 'dota2protips.com' },
      { protocol: 'https', hostname: '*.dota2protips.com' },
      { protocol: 'https', hostname: '**' },
    ],
  },
  async redirects() {
    return [
      // ── Blog listing ──────────────────────────────────────────────────────
      { source: '/blog', destination: '/blog', permanent: true },

      // ── Teams ─────────────────────────────────────────────────────────────
      { source: '/mouz-esports',   destination: '/teams/mouz-esports',   permanent: true },
      { source: '/xtreme-gaming',  destination: '/teams/xtreme-gaming',  permanent: true },
      { source: '/tundra-esports', destination: '/teams/tundra-esports', permanent: true },
      { source: '/og',             destination: '/teams/og',             permanent: true },
      { source: '/team-liquid',    destination: '/teams/team-liquid',    permanent: true },
      { source: '/team-yandex',    destination: '/teams/team-yandex',    permanent: true },
      { source: '/team-spirit',    destination: '/teams/team-spirit',    permanent: true },
      { source: '/aurora-gaming',  destination: '/teams/aurora-gaming',  permanent: true },
      { source: '/betboom-team',   destination: '/teams/betboom-team',   permanent: true },
      { source: '/team-falcons',   destination: '/teams/team-falcons',   permanent: true },
      { source: '/parivision',     destination: '/teams/parivision',     permanent: true },

      // ── Players ───────────────────────────────────────────────────────────
      { source: '/pure',                              destination: '/players/pure',          permanent: true },
      { source: '/bzm',                               destination: '/players/bzm',           permanent: true },
      { source: '/chira_junior',                      destination: '/players/chira_junior',  permanent: true },
      { source: '/noticed',                           destination: '/players/noticed',       permanent: true },
      { source: '/saksa',                             destination: '/players/saksa',         permanent: true },
      { source: '/malady',                            destination: '/players/malady',        permanent: true },
      { source: '/watson',                            destination: '/players/watson',        permanent: true },
      { source: '/skiter',                            destination: '/players/skiter',        permanent: true },
      { source: '/atf',                               destination: '/players/atf',           permanent: true },
      { source: '/malr1ne',                           destination: '/players/malr1ne',       permanent: true },
      { source: '/sneyking',                          destination: '/players/sneyking',      permanent: true },
      { source: '/cr1t',                              destination: '/players/cr1t',          permanent: true },
      { source: '/mira',                              destination: '/players/mira',          permanent: true },
      { source: '/boxi',                              destination: '/players/boxi',          permanent: true },
      { source: '/micke',                             destination: '/players/micke',         permanent: true },
      { source: '/torontotokyo',                      destination: '/players/torontotokyo',  permanent: true },
      { source: '/nightfall',                         destination: '/players/nightfall',     permanent: true },
      { source: '/kiyotaka',                          destination: '/players/kiyotaka',      permanent: true },
      { source: '/collapse-dota-2-player-biography', destination: '/players/collapse',      permanent: true },
      { source: '/noone',                             destination: '/players/noone',         permanent: true },
      { source: '/gpk',                               destination: '/players/gpk',           permanent: true },
      { source: '/yatoro',                            destination: '/players/yatoro',        permanent: true },
      { source: '/satanic',                           destination: '/players/satanic',       permanent: true },
      { source: '/nisha',                             destination: '/players/nisha',         permanent: true },
      { source: '/ace',                               destination: '/players/ace',           permanent: true },
      { source: '/tofu',                              destination: '/players/tofu',          permanent: true },
      { source: '/panto',                             destination: '/players/panto',         permanent: true },
      { source: '/insania',                           destination: '/players/insania',       permanent: true },
      { source: '/saberlight',                        destination: '/players/saberlight',    permanent: true },
      { source: '/miposhka',                          destination: '/players/miposhka',      permanent: true },
      { source: '/9class',                            destination: '/players/9class',        permanent: true },
      { source: '/dukalis',                           destination: '/players/dukalis',       permanent: true },
      { source: '/dm',                                destination: '/players/dm',            permanent: true },
      { source: '/miero',                             destination: '/players/miero',         permanent: true },
      { source: '/save',                              destination: '/players/save',          permanent: true },
      { source: '/kataomi',                           destination: '/players/kataomi',       permanent: true },
      { source: '/rue',                               destination: '/players/rue',           permanent: true },
      { source: '/larl',                              destination: '/players/larl',          permanent: true },

      // ── Tournaments ───────────────────────────────────────────────────────
      { source: '/dreamleague-season-28-predictions',                      destination: '/tournaments/dreamleague-season-28',      permanent: true },
      { source: '/pgl-wallachia-season-7-predictions',                     destination: '/tournaments/pgl-wallachia-season-7',     permanent: true },
      { source: '/blast-slam-vi-predictions',                              destination: '/tournaments/blast-slam-vi',              permanent: true },
      { source: '/fissure-universe-episode-8-predictions',                 destination: '/tournaments/fissure-universe-episode-8', permanent: true },
      { source: '/fissure-universe-episode-6-play-in-predictions',         destination: '/tournaments/fissure-universe-episode-6', permanent: true },
      { source: '/fissure-universe-episode-5-predictions',                 destination: '/tournaments/fissure-universe-episode-5', permanent: true },
      { source: '/dreamleague-season-27-predictions',                      destination: '/tournaments/dreamleague-season-27',      permanent: true },
      { source: '/who-will-win-dota2-dreamleague-season-25',               destination: '/tournaments/dreamleague-season-25',      permanent: true },
      { source: '/dota2-predictions-dreamleague-season-25-group-stage-2',  destination: '/tournaments/dreamleague-season-25',      permanent: true },
      { source: '/dota2-predictions-dreamleague-season-25-group-stage-day-1', destination: '/tournaments/dreamleague-season-25',   permanent: true },
      { source: '/dota2-predictions-dreamleague-season-25-group-stage-day-2', destination: '/tournaments/dreamleague-season-25',   permanent: true },
      { source: '/dota2-predictions-dreamleague-season-25-group-stage-day-3', destination: '/tournaments/dreamleague-season-25',   permanent: true },
      { source: '/dota2-predictions-dreamleague-season-25-group-stage-day-4', destination: '/tournaments/dreamleague-season-25',   permanent: true },
      { source: '/who-will-win-esl-one-raleigh-2025',                      destination: '/tournaments/esl-one-raleigh-2025',       permanent: true },
      { source: '/dota2-predictions-esl-one-raleigh-2025-group-stage-day-1', destination: '/tournaments/esl-one-raleigh-2025',     permanent: true },
      { source: '/dota2-predictions-esl-one-raleigh-2025-group-stage-day-3', destination: '/tournaments/esl-one-raleigh-2025',     permanent: true },
      { source: '/the-international-2025-group-stage-predictions',          destination: '/tournaments/the-international-2025',    permanent: true },
      { source: '/who-will-win-the-international-2025-predictions',         destination: '/tournaments/the-international-2025',    permanent: true },
      { source: '/the-international-2025-china-closed-qualifier',           destination: '/tournaments/the-international-2025',    permanent: true },
      { source: '/the-international-2025-north-america-closed-qualifier',   destination: '/tournaments/the-international-2025',    permanent: true },
      { source: '/the-international-2025-western-europe-closed-qualifier',  destination: '/tournaments/the-international-2025',    permanent: true },
      { source: '/the-international-2025-eastern-europe-closed-qualifier',  destination: '/tournaments/the-international-2025',    permanent: true },
      { source: '/the-international-2025-south-america-closed-qualifier',   destination: '/tournaments/the-international-2025',    permanent: true },
      { source: '/dota-2-clavision-masters-2025-predictions',               destination: '/tournaments/clavision-masters-2025',    permanent: true },
      { source: '/dota-2-esports-world-cup-2025-predictions',               destination: '/tournaments/esports-world-cup-2025',    permanent: true },
      { source: '/predictions-who-will-win-pgl-wallachia-season-5',         destination: '/tournaments/pgl-wallachia-season-5',    permanent: true },
      { source: '/pgl-wallachia-season-5-playoffs',                         destination: '/tournaments/pgl-wallachia-season-5',    permanent: true },
      { source: '/pgl-wallachia-season-5-group-stage-day-1-predictions',    destination: '/tournaments/pgl-wallachia-season-5',    permanent: true },
      { source: '/pgl-wallachia-season-5-group-stage-day-2-predictions',    destination: '/tournaments/pgl-wallachia-season-5',    permanent: true },
      { source: '/pgl-wallachia-season-5-group-stage-day-3-predictions',    destination: '/tournaments/pgl-wallachia-season-5',    permanent: true },
      { source: '/pgl-wallachia-season-5-group-stage-day-4-predictions',    destination: '/tournaments/pgl-wallachia-season-5',    permanent: true },

      // ── Blog/news articles with no equivalent → home ──────────────────────
      { source: '/mirana-lore',                                   destination: '/', permanent: true },
      { source: '/slark-the-shadow-of-dark-reef',                 destination: '/', permanent: true },
      { source: '/dota-2-transfers',                              destination: '/', permanent: true },
      { source: '/best-mid-players-of-the-2025-season',           destination: '/', permanent: true },
      { source: '/best-dota2-mid-pro-players-2024-season',        destination: '/', permanent: true },
      { source: '/how-much-money-dota-pro-players-make',          destination: '/', permanent: true },
      { source: '/nigma-galaxy-part-ways-with-ta2000',            destination: '/', permanent: true },
      { source: '/sumail-stan-in-for-falcons-in-dreamleague-season-25', destination: '/', permanent: true },
      { source: '/9pandas-solo-what-motivates-you-to-play-pro-dota',   destination: '/', permanent: true },
      { source: '/satanic-parivision-inteview',                   destination: '/', permanent: true },
      { source: '/dota2-predictions-dreamleague-season-25-group-stage-day-3', destination: '/tournaments/dreamleague-season-25', permanent: true },
    ]
  },
};

export default nextConfig;
